In [1]:
import numpy as np
from qiskit import QuantumCircuit
import matplotlib.pyplot as plt

# Set matplotlib backend explicitly
plt.switch_backend('Agg')

def create_simple_combined_circuit():
    """Create a simple 2-qubit circuit with both RXX and RYY gates using β parameter"""
    from qiskit.circuit import Parameter
    
    qc = QuantumCircuit(2)
    
    # Define β as a parameter
    beta = Parameter('β')
    
    # Apply RXX gate first with β parameter
    qc.rxx(beta, 0, 1)  # RXX between qubits 0 and 1
    
    # Apply RYY gate second with β parameter  
    qc.ryy(beta, 0, 1)  # RYY between qubits 0 and 1
    
    return qc

# Create the circuit
simple_circuit = create_simple_combined_circuit()

# Print text representation
print("Simple 2-Qubit Circuit with RXX(β) and RYY(β) gates:")
print(simple_circuit.draw())

# Save circuit diagram function
def save_circuit_diagram(circuit, filename, title):
    """Save circuit diagram as an image file"""
    try:
        # Create the figure using qiskit's draw method
        fig = circuit.draw(output='mpl', style='iqp')
        
        # Add title to the figure
        #fig.suptitle(title, fontsize=16)
        
        # Adjust layout
        fig.tight_layout()
        
        # Save the figure
        fig.savefig(filename, dpi=300, bbox_inches='tight')
        
        # Close the figure to free memory
        plt.close(fig)
        
        print(f"Saved {title} diagram as {filename}")
        
    except Exception as e:
        print(f"Error saving diagram: {e}")

# Save the diagram
save_circuit_diagram(simple_circuit, 'simple_rxx_ryy_beta.png', 
                    'Simple 2-Qubit Circuit: RXX(β) + RYY(β)')

# Check if file was created
import os
if os.path.exists('simple_rxx_ryy_beta.png'):
    file_size = os.path.getsize('simple_rxx_ryy_beta.png')
    print(f"✓ simple_rxx_ryy_beta.png - Created successfully ({file_size} bytes)")
else:
    print("✗ File not created")

print("\nDone! You now have a simple 2-qubit circuit with RXX(β) followed by RYY(β).")

Simple 2-Qubit Circuit with RXX(β) and RYY(β) gates:
     ┌─────────┐┌─────────┐
q_0: ┤0        ├┤0        ├
     │  Rxx(β) ││  Ryy(β) │
q_1: ┤1        ├┤1        ├
     └─────────┘└─────────┘
Saved Simple 2-Qubit Circuit: RXX(β) + RYY(β) diagram as simple_rxx_ryy_beta.png
✓ simple_rxx_ryy_beta.png - Created successfully (14298 bytes)

Done! You now have a simple 2-qubit circuit with RXX(β) followed by RYY(β).


In [2]:
import numpy as np

print("=" * 80)
print("INDIVIDUAL 8×8 MATRICES FOR PAIRWISE XY MIXERS (3 QUBITS)")
print("=" * 80)

# Define Pauli matrices
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -1j], [1j, 0]])
I = np.array([[1, 0], [0, 1]])

print("\nPauli matrices:")
print("X =", X)
print("Y =", Y) 
print("I =", I)

# Helper function to create 3-qubit tensor products
def tensor_product_3qubit(op1, op2, op3):
    """Create tensor product of three 2x2 operators"""
    return np.kron(np.kron(op1, op2), op3)

# Basis states for reference
basis_states = ['|000⟩', '|001⟩', '|010⟩', '|011⟩', '|100⟩', '|101⟩', '|110⟩', '|111⟩']
print(f"\nBasis states: {basis_states}")
print("Matrix indices:  0      1      2      3      4      5      6      7")

print("\n" + "=" * 80)
print("1. FIRST PAIRWISE MIXER: H₁₂ = X₁X₂ + Y₁Y₂ (qubits 1 and 2)")
print("=" * 80)

# Calculate X₁X₂ term (X⊗X⊗I)
XX_12 = tensor_product_3qubit(X, X, I)
print("\nX₁X₂ matrix (X⊗X⊗I):")
print("Real part:")
print(np.real(XX_12).astype(int))
print("Imaginary part:")
print(np.imag(XX_12).astype(int))

# Calculate Y₁Y₂ term (Y⊗Y⊗I)  
YY_12 = tensor_product_3qubit(Y, Y, I)
print("\nY₁Y₂ matrix (Y⊗Y⊗I):")
print("Real part:")
print(np.real(YY_12).astype(int))
print("Imaginary part:")
print(np.imag(YY_12).astype(int))

# Combined H₁₂
H_12 = XX_12 + YY_12
print("\nH₁₂ = X₁X₂ + Y₁Y₂:")
print("Real part:")
print(np.real(H_12).astype(int))
print("Imaginary part:")
print(np.imag(H_12).astype(int))

print("\n" + "=" * 80)
print("2. SECOND PAIRWISE MIXER: H₂₃ = X₂X₃ + Y₂Y₃ (qubits 2 and 3)")
print("=" * 80)

# Calculate X₂X₃ term (I⊗X⊗X)
XX_23 = tensor_product_3qubit(I, X, X)
print("\nX₂X₃ matrix (I⊗X⊗X):")
print("Real part:")
print(np.real(XX_23).astype(int))
print("Imaginary part:")
print(np.imag(XX_23).astype(int))

# Calculate Y₂Y₃ term (I⊗Y⊗Y)
YY_23 = tensor_product_3qubit(I, Y, Y)
print("\nY₂Y₃ matrix (I⊗Y⊗Y):")
print("Real part:")
print(np.real(YY_23).astype(int))
print("Imaginary part:")
print(np.imag(YY_23).astype(int))

# Combined H₂₃
H_23 = XX_23 + YY_23
print("\nH₂₃ = X₂X₃ + Y₂Y₃:")
print("Real part:")
print(np.real(H_23).astype(int))
print("Imaginary part:")
print(np.imag(H_23).astype(int))

print("\n" + "=" * 80)
print("3. THIRD PAIRWISE MIXER: H₁₃ = X₁X₃ + Y₁Y₃ (qubits 1 and 3)")
print("=" * 80)

# Calculate X₁X₃ term (X⊗I⊗X)
XX_13 = tensor_product_3qubit(X, I, X)
print("\nX₁X₃ matrix (X⊗I⊗X):")
print("Real part:")
print(np.real(XX_13).astype(int))
print("Imaginary part:")
print(np.imag(XX_13).astype(int))

# Calculate Y₁Y₃ term (Y⊗I⊗Y)
YY_13 = tensor_product_3qubit(Y, I, Y)
print("\nY₁Y₃ matrix (Y⊗I⊗Y):")
print("Real part:")
print(np.real(YY_13).astype(int))
print("Imaginary part:")
print(np.imag(YY_13).astype(int))

# Combined H₁₃
H_13 = XX_13 + YY_13
print("\nH₁₃ = X₁X₃ + Y₁Y₃:")
print("Real part:")
print(np.real(H_13).astype(int))
print("Imaginary part:")
print(np.imag(H_13).astype(int))

print("\n" + "=" * 80)
print("4. VERIFICATION: TOTAL XY MIXER")
print("=" * 80)

# Total H_XY should equal sum of all three
H_XY_total = H_12 + H_23 + H_13
print("\nH_XY = H₁₂ + H₂₃ + H₁₃:")
print("Real part:")
print(np.real(H_XY_total).astype(int))
print("Imaginary part:")
print(np.imag(H_XY_total).astype(int))

print("\n" + "=" * 80)
print("5. ANALYSIS OF MATRIX STRUCTURE")
print("=" * 80)

print("\nNon-zero pattern analysis:")
for i, (name, matrix) in enumerate([("H₁₂", H_12), ("H₂₃", H_23), ("H₁₃", H_13)]):
    non_zero_positions = np.where(np.abs(matrix) > 1e-10)
    print(f"\n{name} has non-zero elements at positions:")
    for row, col in zip(non_zero_positions[0], non_zero_positions[1]):
        value = matrix[row, col]
        state_from = basis_states[row]
        state_to = basis_states[col]
        print(f"  ({row},{col}): {state_from} ↔ {state_to}, value = {value}")

print("\n" + "=" * 80)
print("6. EXCITATION NUMBER ANALYSIS")
print("=" * 80)

# Show which states connect to which for each mixer
excitation_numbers = [0, 1, 1, 2, 1, 2, 2, 3]  # for each basis state

print("\nExcitation numbers by state:")
for i, (state, exc) in enumerate(zip(basis_states, excitation_numbers)):
    print(f"  {i}: {state} → {exc} excitations")

print("\nEach pairwise mixer preserves excitation number and connects states")
print("that differ by swapping bits in the two involved qubits.")

print("\n" + "=" * 80)
print("ANALYSIS COMPLETE")
print("=" * 80)

INDIVIDUAL 8×8 MATRICES FOR PAIRWISE XY MIXERS (3 QUBITS)

Pauli matrices:
X = [[0 1]
 [1 0]]
Y = [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
I = [[1 0]
 [0 1]]

Basis states: ['|000⟩', '|001⟩', '|010⟩', '|011⟩', '|100⟩', '|101⟩', '|110⟩', '|111⟩']
Matrix indices:  0      1      2      3      4      5      6      7

1. FIRST PAIRWISE MIXER: H₁₂ = X₁X₂ + Y₁Y₂ (qubits 1 and 2)

X₁X₂ matrix (X⊗X⊗I):
Real part:
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Imaginary part:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Y₁Y₂ matrix (Y⊗Y⊗I):
Real part:
[[ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [-1  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0]]
Imaginary part:
[[0 0 